logging.level.com.reliaquest: DEBUG
spring.application.name: mock-employee-api
server:
  port: 8112
  compression:
    enabled: true
mock.employees.max: 50
springdoc:
  api-docs:
    path: /v3/api-docs